[build]
  builder = "python3"
  command = "pip install -r requirements.txt"

[deploy]
  start = "gunicorn app:app"  # Agar 'app' sizning ilovangiz bo'lsa

# Buni olib tashlang, chunki u redundant
# start = "python spofity.py"
